apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: bitnami/etcd:3.5.11
          ports:
            - containerPort: 2379
          env:
            - name: ETCD_ENABLE_V2
              value: "true"
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://etcd:2379"
            - name: ETCD_LISTEN_CLIENT_URLS
              value: "http://0.0.0.0:2379"
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: default
spec:
  selector:
    app: etcd
  ports:
    - name: "2379-tcp"
      port: 2379
      targetPort: 2379
      protocol: TCP